register:
  center:
    config:
      zk:
        zkServers: bidev191:2181
rpc:
  server:
    config:
      serviceName: net.sea.demo.service
      serviceIp: 192.168.4.64
      port: 2001
      opened: true
spring:
  profiles:
    active: zk-reg-center