register:
  center:
    config:
      zk:
        enable: false
        zkServers: localhost:2181
        sessionTimeout: 60000
        connectionTimeout: 60000
      nacos:
        enable: true
        serverAddresses: 127.0.0.1:8848
        needAuth: true
        username: nacos
        password: nacos
rpc:
  server:
    config:
      serviceName: net.sea.demo.service
      serviceIp: 192.168.2.86
      port: 12001
      opened: true
      heartPeriod: 60000
      version: 1.0
spring:
  profiles:
#    active: zk-reg-center
    #引用zk注册中心配置
#    include: zk-reg-center
    #引用nacos注册中心配置
#    include: nacos-reg-center